name: Build on Tags

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Create Archive and Builds Dir
        run: |
          mkdir archives
          mkdir builds

      - name: Tag name
        run: |
          echo "Tag name: ${GITHUB_REF#refs/tags/}"

      - name: Build for Linux x86
        run: GOOS=linux GOARCH=amd64 go  build -ldflags "-X 'main.version=${GITHUB_REF#refs/tags/}'" -o jt jt.go

      - name: Create Linux Archives x86
        run: |
          tar -czvf archives/jt-linux_x86_64.tar.gz jt
        working-directory: ${{ github.workspace }}

      - name: Build for Linux arm64
        run: GOOS=linux GOARCH=arm64 go build -o jt jt.go

      - name: Create Linux Archives arm64
        run: |
          tar -czvf archives/jt-linux_arm64.tar.gz jt
        working-directory: ${{ github.workspace }}

      - name: Build for macOS x86
        run: GOOS=darwin GOARCH=amd64 go build -o jt jt.go

      - name: Create macos Archives x86
        run: |
          tar -czvf archives/jt-macos-intel.tar.gz jt
        working-directory: ${{ github.workspace }}

      - name: Build for macOS Arm
        run: GOOS=darwin GOARCH=arm64 go build -ldflags "-X 'main.version=${GITHUB_REF#refs/tags/}'" -o jt jt.go

      - name: Create macos Archives Arm
        run: |
          tar -czvf archives/jt-macos-arm.tar.gz jt
        working-directory: ${{ github.workspace }}

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o jt.exe

      - name: Create Windows Archives
        run: |
          zip -r archives/jt-windows.zip jt.exe
        working-directory: ${{ github.workspace }}

      - name: Upload Builds
        uses: actions/upload-artifact@v2
        with:
          name: archives
          path: archives

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: archives/*
          prerelease: false
          token: ${{ secrets.GO_JT_BUILD }}
